documented computing selection probabilities
Signed-off-by: Tim Henderson <tadh@case.edu>

diff --git a/bin/graple-selection-probabilities b/bin/graple-selection-probabilities
--- a/bin/graple-selection-probabilities
+++ b/bin/graple-selection-probabilities
@@ -9,8 +9,8 @@ else
 	exit 1
 fi
 
-if ! which selection_probability &> /dev/null; then
-	echo "selection_probability program not found"
+if ! which sel-pr &> /dev/null; then
+	echo "sel-pr program not found"
 	exit 1
 fi
 
@@ -23,7 +23,7 @@ PATHS=$(
 )
 
 for path in $PATHS; do
-	cmd="selection_probability -m $path -o $(dirname $path)/pattern.pr"
+	cmd="sel-pr -m $path -o $(dirname $path)/pattern.pr"
 	echo $cmd
 	$cmd
 done
